language: go

go:
  - 1.9.2

addons:
  ssh_known_hosts: monicalent.com

notifications:
  email:
    on_success: never
    on_failure: always   

git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_285ce119f0f4_key -iv $encrypted_285ce119f0f4_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - go get -v github.com/gohugoio/hugo

script:
  - hugo -d public

after_success:
  - bash ./deploy.sh
