baseurl = "http://monicalent.com/blog/"
title = "Blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Monica Lent"
googleAnalytics = "UA-40399378-2"
paginate = 10
paginatePath = "page"

[Author]
    name = "Monica"
    profile = "http://monicalent.com"

[Taxonomies]
    tag = "tags"

[Params]
    headline = "Blog"
    description = "My tech blog, covering javascript, python, and fun unix tricks I learn while developing software."
    github = "https://github.com/mlent"
    gplus = "https://google.com/+MonicaLent"
    twitter = "https://twitter.com/monicalent"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Website"
    url = "http://monicalent.com/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "http://monicalent.com/#about"
    weight = 4

