baseurl = "https://monicalent.com/blog/"
title = "Monica Lent's Blog"
theme = "pickles"
languageCode = "en-us"
copyright = "&copy; Monica Lent 2017"
paginate = 5
paginatePath = "page"

[Author]
    name = "Monica"
    profile = "https://monicalent.com"

[Taxonomies]
    tag = "tags"

[Params]
    headline = "Monica Lent's Blog"
    description = "A software development blog with a dash of unix. You probably got here by googling an error message ^_^"
    subtitle = "A software development blog with a dash of unix. You probably got here by googling an error message ^_^"
    logo = "/../images/favicon.png"
    favicon = "/../images/favicon.png"
    github = "mlent"
    gplus = "https://google.com/+MonicaLent"
    twitter = "monicalent"
    ga_api_key = "UA-40399378-2"
    avatar = "https://monicalent.com/assets/images/image01.jpg"
    author = "Monica Lent"
    authorwebsite = "http://monicalent.com"
    bio = "Software developer, currently living and working in Berlin."
    contact = "lent.monica@gmail.com"
    linkedin = "monica-lent-542122145"
    disqus = "monicalent"

[Permalinks]
    posts = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Website"
    url = "https://monicalent.com/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "https://monicalent.com/#about"
    weight = 4

